import type { ActionTypesBase, StateBase } from './types';

export const ActionTypes: ActionTypesBase = {
  COMPANY_DELETE_REQUEST: '@oauth/COMPANY_DELETE_REQUEST',
  COMPANY_DELETE_SUCCESS: '@oauth/COMPANY_DELETE_SUCCESS',
  COMPANY_DELETE_FAILURE: '@oauth/COMPANY_DELETE_FAILURE',

  COMPANY_LIST_REQUEST: '@oauth/COMPANY_LIST_REQUEST',
  COMPANY_LIST_SUCCESS: '@oauth/COMPANY_LIST_SUCCESS',
  COMPANY_LIST_FAILURE: '@oauth/COMPANY_LIST_FAILURE',

  COMPANY_ADD_REQUEST: '@oauth/COMPANY_ADD_REQUEST',
  COMPANY_ADD_SUCCESS: '@oauth/COMPANY_ADD_SUCCESS',
  COMPANY_ADD_FAILURE: '@oauth/COMPANY_ADD_FAILURE',

  COMPANY_FIND_REQUEST: '@oauth/COMPANY_FIND_REQUEST',
  COMPANY_FIND_SUCCESS: '@oauth/COMPANY_FIND_SUCCESS',
  COMPANY_FIND_FAILURE: '@oauth/COMPANY_FIND_FAILURE',

  COMPANY_UPDATE_REQUEST: '@oauth/COMPANY_UPDATE_REQUEST',
  COMPANY_UPDATE_SUCCESS: '@oauth/COMPANY_UPDATE_SUCCESS',
  COMPANY_UPDATE_FAILURE: '@oauth/COMPANY_UPDATE_FAILURE',
};

export const InitialState: StateBase = {
  item: null,
  itemEdit: null,
  error: false,
  loading: false,
};
